apiVersion: v1
kind: Endpoints
metadata:
  name: pve-cobi-forwarder
subsets:
  - addresses:
      - ip: 192.168.56.1
    ports:
      - port: 8006
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: pve-cobi-forwarder
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8006
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pve-cobi-forwarder
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    external-dns.alpha.kubernetes.io/hostname: "pve-cobi.tuana9a.com"
    external-dns.alpha.kubernetes.io/target: "zione.tuana9a.com"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - "pve-cobi.tuana9a.com"
      secretName: pve-cobi-tuana9a-com-tls
  rules:
    - host: "pve-cobi.tuana9a.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: pve-cobi-forwarder
                port:
                  number: 443
