#!/usr/bin/env bash
set -euo pipefail

#!/usr/bin/env bash
set -euo pipefail

key_file=$1
ssh_user=$2
node_ip=$3
is_control_plane=$4

kube_join_command_txt="./kube_join_command.tmp.txt"
./wait_for_file.sh $kube_join_command_txt # NOTE: should be generated by ./get_join_command.sh at this point

SSH_OPTS=(-o StrictHostKeyChecking=no -i "${key_file}")

JOIN_OPTS=""
if [[ "$is_control_plane" == "1" ]]; then
  JOIN_OPTS+="--control-plane"
fi

SSH_OPTS=(-o StrictHostKeyChecking=no -i "$key_file")

ssh ${SSH_OPTS[@]} "$ssh_user@$node_ip" \
  "set -euo pipefail; sudo $(cat $kube_join_command_txt) $JOIN_OPTS"