#!/usr/bin/env bash
set -euo pipefail

key_file=$1
ssh_user=$2
node_ip=$3
is_control_plane=$4

if [[ "$is_control_plane" != "1" ]]; then
  echo "Not control plane, skipping..."
  exit 0
fi

kube_certs_txt=./kube_certs.tmp.txt
./wait_for_file.sh $kube_certs_txt # NOTE: should be generated by ./get_kube_certs.sh at this point

SSH_OPTS=(-o StrictHostKeyChecking=no -i "${key_file}")

ssh ${SSH_OPTS[@]} $ssh_user@$node_ip "set -euo pipefail; sudo mkdir -p /etc/kubernetes/pki/etcd/ && sudo chmod 0755 /etc/kubernetes/pki /etc/kubernetes/pki"

while read -r cert_path cert_b64; do
    # skip blank lines
    [[ -z "${cert_path}" ]] && continue

    echo "==> cert_path: ${cert_path}"
    echo "    cert_b64:  ${cert_b64:0:40}..."   # print truncated preview only

    # your logic here, e.g.:
    # echo "${cert_b64}" | base64 -d > "$(basename "${cert_path}")"

    # NOTE: the -n flag is for fixing ssh-eats-your-loop's-stdin bug
    ssh -n ${SSH_OPTS[@]} $ssh_user@$node_ip \
      "set -euo pipefail; echo -n \"${cert_b64}\" | base64 -d | sudo install /dev/stdin -m 0644 ${cert_path}"
done < "$kube_certs_txt"
