- hosts: tuana9a-dev2
  tasks:
    - import_tasks: ./tasks/wireguard_client.yml
    - import_tasks: ./tasks/install_haproxy.yml
    - name: Print haproxy.cfg
      debug:
        msg: "{{ lookup('template', './templates/tuana9a-dev2/haproxy.cfg') | split('\n') }}"
    - name: Confirm update
      pause:
        prompt: "Do you want to proceed with these servers? (yes/no)"
      register: confirm_update_result
    - name: Cancel update haproxy
      meta: end_play
      when: confirm_update_result.user_input != 'yes'
    - name: Update haproxy cfg
      become: true
      template:
        src: "./templates/tuana9a-dev2/haproxy.cfg"
        dest: "/etc/haproxy/haproxy.cfg"
    - name: Reload haproxy service
      become: true
      ansible.builtin.service:
        name: haproxy
        state: reloaded
