kubeProxyReplacement: true
k8sServiceHost: 192.168.56.21
k8sServicePort: 6443
ipam:
  # -- Configure IP Address Management mode.
  # ref: https://docs.cilium.io/en/stable/network/concepts/ipam/
  mode: "cluster-pool"
  operator:
    clusterPoolIPv4PodCIDRList: ["10.244.0.0/16"]
hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: false
  metrics:
    enabled:
      - icmp
      - dns:query;labelsContext=source_ip,destination_ip,source_pod,destination_pod,source_namespace,destination_namespace,traffic_direction
      - flow:labelsContext=source_ip,destination_ip,source_pod,destination_pod,source_namespace,destination_namespace,traffic_direction
      - tcp:labelsContext=source_ip,destination_ip,source_pod,destination_pod,source_namespace,destination_namespace,traffic_direction
      - httpV2:labelsContext=source_ip,destination_ip,source_pod,destination_pod,source_namespace,destination_namespace,traffic_direction
      - drop:labelsContext=source_ip,destination_ip,source_pod,destination_pod,source_namespace,destination_namespace,traffic_direction
prometheus:
  enabled: true
operator:
  prometheus:
    enabled: true
