apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 600-k8s-forwarder
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 10
  source:
    path: 600-k8s-forwarder-manifests
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: rock-n-roll
  destination:
    server: https://kubernetes.default.svc
    namespace: k8s-forwarder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
