controller:
  JCasC:
    configScripts:
      oidc: |
        credentials:
          system:
            domainCredentials:
            - credentials:
              - idTokenFile:
                  id: gcp-oidc-id-token
                  scope: GLOBAL
                  audience: "https://iam.googleapis.com/projects/474326114337/locations/global/workloadIdentityPools/jenkins/providers/jenkins-tuana9a-com"
              - idTokenFile:
                  id: aws-oidc-id-token
                  scope: GLOBAL
                  audience: "sts.amazonaws.com"
