apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: jcasc-appearance
  labels:
    jenkins-jenkins-config: "true"
data:
  appearance.yaml: |
    appearance:
      themeManager:
        disableUserThemes: true
        theme: "darkSystem" # use 'dark' for forcing the dark theme regardless of OS settings
