apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: main-jcasc
  labels:
    jenkins-jenkins-config: "true"
data:
  # https://github.com/jenkinsci/matrix-auth-plugin/blob/50ec01b320a33d7eb2d649bd40bcc97221f50a79/src/test/resources/org/jenkinsci/plugins/matrixauth/integrations/casc/configuration-as-code-v3.yml#L1
  auth.yaml: |
    jenkins:
      securityRealm:
        googleOAuth2:
          clientId: "474326114337-pcipbac6h46bg87qg8jr9p757npg1j1a.apps.googleusercontent.com"
          clientSecret: "${google-login-client-secret}" # https://github.com/jenkinsci/helm-charts/blob/018948716bf31ff168e54a62eba504712010eb21/charts/jenkins/templates/jenkins-controller-statefulset.yaml#L383
      authorizationStrategy:
        projectMatrix:
          entries:
            - user:
                name: anonymous
                permissions: []
            - user:
                name: tuana9a@gmail.com
                permissions:
                  - Overall/Administer

  oidc.yaml: |
    credentials:
      system:
        domainCredentials:
          - credentials:
              - idTokenFile:
                  id: gcp-oidc-id-token
                  scope: GLOBAL
                  audience: "https://iam.googleapis.com/projects/474326114337/locations/global/workloadIdentityPools/jenkins/providers/jenkins-tuana9a-com"
              - idTokenFile:
                  id: aws-oidc-id-token
                  scope: GLOBAL
                  audience: "sts.amazonaws.com"

  timestamper.yaml: |
    unclassified:
      timestamper:
        allPipelines: true

  appearance.yaml: |
    appearance:
      themeManager:
        disableUserThemes: true
        theme: "darkSystem" # use 'dark' for forcing the dark theme regardless of OS settings
