apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: main-jcasc
  labels:
    jenkins-jenkins-config: "true"
data:
  auth.yaml: |
    jenkins:
      securityRealm:
        googleOAuth2:
          clientId: "${google-login-client-id}"
          clientSecret: "${google-login-client-secret}"
      authorizationStrategy:
        projectMatrix:
          entries:
            - user:
                name: anonymous
                permissions: []
            - user:
                name: tuana9a@gmail.com
                permissions:
                  - Overall/Administer

  oidc.yaml: |
    credentials:
      system:
        domainCredentials:
          - credentials:
              - idTokenFile:
                  id: gcp-oidc-id-token
                  scope: GLOBAL
                  audience: "https://iam.googleapis.com/projects/474326114337/locations/global/workloadIdentityPools/jenkins/providers/jenkins-tuana9a-com"
              - idTokenFile:
                  id: aws-oidc-id-token
                  scope: GLOBAL
                  audience: "sts.amazonaws.com"

  timestamper.yaml: |
    unclassified:
      timestamper:
        allPipelines: true

  appearance.yaml: |
    appearance:
      themeManager:
        disableUserThemes: true
        theme: "darkSystem" # use 'dark' for forcing the dark theme regardless of OS settings
