apiVersion: v1
kind: ConfigMap
metadata:
  namespace: jenkins
  name: timestamper-jcasc
  labels:
    jenkins-jenkins-config: "true"
data:
  timestamper.yaml: |
    unclassified:
      timestamper:
        allPipelines: true
