groups:
  - name: AllInstances
    rules:
      - alert: HighMemoryUsage
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 15
        for: 5m
        labels:
          severity: warning
        annotations:
          description: High ram usage ({{ $value | printf "%.2f" }}% left)
      - alert: NodeDown
        expr: up == 0
        for: 5m
        labels:
          severity: warning
        annotations:
          description: "{{ $labels.instance }} is down"
      - alert: LowDiskSpace
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} * 100 < 20
        for: 1h
        labels:
          severity: warning
        annotations:
          description: Low disk space ({{ $value | printf "%.2f" }}% left)
