- hosts: nfs
  tasks:
    # - import_tasks: ./tasks/cronjob_authorized_keys.yml
    # - import_tasks: ./tasks/set_timezone.yml
    # - import_tasks: ./tasks/set_hostname.yml
    - import_tasks: ./tasks/install_awscli.yml
    - import_tasks: ./tasks/install_node_exporter.yml
    - import_tasks: ./tasks/install_nfs_server.yml
    - import_tasks: ./tasks/install_parted.yml
