- hosts: tuana9a_dev
  tasks:
    - import_tasks: ./tasks/parted.yml
    - import_tasks: ./tasks/set_timezone.yml
    - import_tasks: ./tasks/set_hostname.yml
    - import_tasks: ./tasks/install_docker.yml
    - import_tasks: ./tasks/add_current_user_to_docker_group.yml
    - import_tasks: ./tasks/install_node_exporter.yml
    - import_tasks: ./tasks/install_openvpn.yml
    - import_tasks: ./tasks/openvpn_client.yml
    - import_tasks: ./tasks/install_wireguard.yml
    - import_tasks: ./tasks/wireguard_client.yml
    - import_tasks: ./tasks/cronjob_update_cloudflare_dns.yml
