- hosts: k8s_control_plane
  tasks:
    - name: Execute the backup script
      ansible.builtin.command: /usr/local/bin/backup-kubernetes.sh
      register: backup_output

    - name: Print stdout
      ansible.builtin.debug:
        msg: "{{ backup_output.stdout.split('\n')}}"

    - name: Print stderr
      ansible.builtin.debug:
        msg: "{{ backup_output.stderr.split('\n')}}"
