apiVersion: v1
kind: Service
metadata:
  namespace: coder
  name: internal
spec:
  clusterIP: None # headless service
  ipFamilyPolicy: SingleStack # WTF: Service "pg-internal" is invalid: [spec.ipFamilyPolicy: Invalid value: "RequireDualStack": this cluster is not configured for dual-stack services, spec.ipFamilies[1]: Invalid value: "IPv6": not configured on this cluster]
  selector:
    internal: "1"
