apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: vmbr56
  namespace: metallb-system
spec:
  addresses:
    - 192.168.56.78-192.168.56.89
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: vmbr56
  namespace: metallb-system
spec:
  ipAddressPools:
    - vmbr56
