HOST_NAME: tuana9a-dev
parted:
  dev_path: /dev/vdb
  mount_path: /data/
openvpn_client_items:
  - file: tuana9a-dev/tuana9a-dev-zephyrus.ovpn
    name: tuana9a-dev-zephyrus
    state: stopped
    enabled: false
wireguard_client_items:
  - file: tuana9a-dev/wg/tuana9a-dev-zpr.conf
    name: wg0
    state: stopped
    enabled: false
update_dns_items:
  - record_name: tuana9a-dev.z.tuana9a.com
    extract_ip: $(/usr/sbin/ip addr show tun0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)
    state: absent
install_python_items:
  - PYTHON_VERSION: "3.8.16"
cronjob_items:
  - name: set_tuana9a-dev.z.tuana9a.com
    cmd: |
      curl -X PUT https://paste.tuana9a.com/tuana9a-dev.z.tuana9a.com -H "Content-Type: text/plain" -d "$(/usr/sbin/ip addr show tun0 | grep 'inet ' | awk '{print $2}' | cut -d/ -f1)"
    minute: "0"
    state: absent
