- name: parted
  loop: "{{ parted }}"
  become: true
  # NOTE: currently only support create one partition
  community.general.parted:
    device: "{{ item.dev_path }}"
    number: 1
    state: present

- name: mkfs.ext4
  loop: "{{ parted }}"
  become: true
  filesystem:
    fstype: ext4
    dev: "{{ item.dev_path }}1"

- name: ensure mount_point
  loop: "{{ parted }}"
  become: true
  file:
    owner: root
    group: root
    state: directory
    path: "{{ item.mount_path }}"

- name: mount
  loop: "{{ parted }}"
  become: true
  mount:
    fstype: ext4
    src: "{{ item.dev_path }}1"
    path: "{{ item.mount_path }}"
    state: mounted
