apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 5070-argo-apps
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 10
  source:
    path: 5070-argo-apps
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: rock-n-roll
  destination:
    server: https://kubernetes.default.svc
