apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: admin-login
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-tuana9a-com
    kind: SecretStore
  target:
    name: admin-login
  dataFrom:
    - extract:
        key: grafana/admin-login
