apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-v2-restore
  namespace: dkhptd
spec:
  template:
    spec:
      initContainers:
        - name: download-backup
          image: amazon/aws-cli:latest
          command:
            - "sh"
            - "-c"
            - |
              OBJECT_KEY=dkhptd/mongo-dump-2024.09.20.tar.gz
              aws s3api --endpoint-url ${S3_ENDPOINT} get-object --bucket ${BUCKET_NAME} --key $OBJECT_KEY /data/dump.tar.gz
              echo =====
              ls -la /data/
          envFrom:
            - configMapRef:
                name: dkhptd-mongo-v2-restore
          volumeMounts:
            - name: workdir
              mountPath: /data

        - name: untar
          image: busybox:latest
          command:
            - "sh"
            - "-c"
            - |
              cd /data
              echo =====
              tar -xzvf dump.tar.gz dump
          volumeMounts:
            - name: workdir
              mountPath: /data

        - name: mongo-restore
          image: mongo:7.0
          command:
            - "sh"
            - "-c"
            - |
              echo =====
              mongorestore $MONGO_CONNECTION_STRING_V2 /data/dump
          envFrom:
            - configMapRef:
                name: dkhptd-mongo-v2-restore
          volumeMounts:
            - name: workdir
              mountPath: /data

      containers:
        - name: dkhptd-mongo-v2-restore
          image: busybox:latest
          command: ["sh", "-c", "echo migration v2 complete"]

      restartPolicy: Never
      volumes:
        - name: workdir
          emptyDir: {}
