apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-v2-migration
  namespace: dkhptd
spec:
  template:
    spec:
      initContainers:
        - name: mongo-dump
          image: mongo:5.0
          command:
            - "sh"
            - "-c"
            - |
              mongodump $MONGO_CONNECTION_STRING --out=/data/dump
              echo ========================
              ls -l /data/dump
          envFrom:
            - configMapRef:
                name: dkhptd-mongo-v2-migration
          volumeMounts:
            - name: workdir
              mountPath: /data

        - name: mongo-restore
          image: mongo:7.0
          command:
            - "sh"
            - "-c"
            - |
              mongorestore $MONGO_CONNECTION_STRING_V2 /data/dump
          envFrom:
            - configMapRef:
                name: dkhptd-mongo-v2-migration
          volumeMounts:
            - name: workdir
              mountPath: /data

      containers:
        - name: dkhptd-mongo-v2-migration
          image: busybox:latest
          command: ["sh", "-c", "echo migration v2 complete"]

      restartPolicy: Never
      volumes:
        - name: workdir
          emptyDir: {}
