apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-namespaces
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: 120-k8s-namespaces
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: bootstrap-gke
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
