apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  source:
    chart: metrics-server
    repoURL: https://kubernetes-sigs.github.io/metrics-server
    targetRevision: 3.12.0
    helm:
      releaseName: metrics-server
      valuesObject:
        replicas: 3
        args: ["--kubelet-insecure-tls"]
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics-server
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
