apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  project: default
  sources:
    - chart: metrics-server
      repoURL: https://kubernetes-sigs.github.io/metrics-server
      targetRevision: 3.12.0
      helm:
        releaseName: metrics-server
        valueFiles:
          - $values/150-metrics-server/values.yaml
    - repoURL: https://github.com/tuana9a/platform.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metrics-server
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
