apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner-vdb
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner-vdb
  namespace: argocd
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      releaseName: nfs-subdir-external-provisioner
      valuesObject:
        replicaCount: 3
        storageClass:
          name: nfs-vdb
        nfs:
          server: 192.168.56.7
          path: /exports/vdb/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs-provisioner-vdb
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner-vdc
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-provisioner-vdc
  namespace: argocd
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
    targetRevision: 4.0.18
    helm:
      releaseName: nfs-subdir-external-provisioner
      valuesObject:
        replicaCount: 3
        storageClass:
          name: nfs-vdc
        nfs:
          server: 192.168.56.7
          path: /exports/vdc/
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nfs-provisioner-vdc
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
