apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csi-nfs-client-manifests
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs-provisioner
  project: default
  revisionHistoryLimit: 10
  source:
    path: 160-csi-nfs-client-manifests
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
