apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 198-vault-secret-stores
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 10
  source:
    path: 198-vault-secret-stores/manifests
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: rock-n-roll
  destination:
    server: https://kubernetes.default.svc.cluster.local
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
