apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  project: default
  revisionHistoryLimit: 10
  source:
    path: 200-cert-manager-issuers-manifests
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
