apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 210-knative-k8s-cobi-tuana9a
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 10
  source:
    path: 210-knative-k8s-cobi-tuana9a
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: rock-n-roll
  destination:
    server: https://kubernetes.default.svc.cluster.local
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: "rbac.authorization.k8s.io"
      kind: "ClusterRole"
      jsonPointers:
        - /rules
    - kind: Namespace
      jsonPointers:
        - /metadata/labels
