apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: promtail
  project: default
  revisionHistoryLimit: 10
  source:
    path: 300-promtail
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: main
  syncPolicy:
    automated:
      # prune: false
      selfHeal: true
