apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 7.3.10
      helm:
        releaseName: grafana
        valueFiles:
          - $values/300-grafana/values.yaml
    - repoURL: https://github.com/tuana9a/platform.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    automated:
      allowEmpty: false
      prune: false
      selfHeal: true
