apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder
  namespace: argocd
spec:
  project: default
  sources:
    - chart: coder
      repoURL: https://helm.coder.com/v2
      targetRevision: 2.14.3
      helm:
        releaseName: coder
        valueFiles:
          - $values/502-coder/values.yaml
    - repoURL: https://github.com/tuana9a/platform.git
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: coder
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
