apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coder-manifests
  namespace: argocd
spec:
  destination:
    namespace: coder
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: 502-coder-manifests
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: main
  syncPolicy:
    automated:
      # prune: false
      selfHeal: true
