apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 511-dkhptd
  namespace: argocd
spec:
  destination:
    namespace: dkhptd
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: 511-dkhptd-manifests
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: main
  syncPolicy:
    automated:
      # prune: false
      selfHeal: true
