apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: 210-knative
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: false
