apiVersion: v1
kind: Namespace
metadata:
  name: t9stbot
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: t9stbot
  namespace: argocd
spec:
  destination:
    namespace: t9stbot
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 10
  source:
    path: 510-t9stbot-manifests
    repoURL: https://github.com/tuana9a/platform.git
    targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
