# NOTE: to fix vault is sealed when spot instances dead, make pod restart
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-unseal
  namespace: vault
spec:
  schedule: "* * * * *" # Adjust the schedule as needed
  # https://stackoverflow.com/questions/51657105/how-to-ensure-kubernetes-cronjob-does-not-restart-on-failure
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      # https://stackoverflow.com/questions/51657105/how-to-ensure-kubernetes-cronjob-does-not-restart-on-failure
      backoffLimit: 0
      template:
        spec:
          # https://stackoverflow.com/questions/51657105/how-to-ensure-kubernetes-cronjob-does-not-restart-on-failure
          restartPolicy: Never
          containers:
            - name: vault-unseal
              image: hashicorp/vault:1.17.2
              command: ["/bin/sh", "-c"]
              args:
                - |
                  for instanceId in $(seq 0 2); do
                    export VAULT_ADDR=http://vault-$instanceId.vault-internal.vault.svc.cluster.local:8200
                    echo "$VAULT_ADDR"

                    is_sealed=$(vault status | grep -i sealed | awk '{print $2}')
                    if [ "$is_sealed" = "false" ]; then
                      echo "vault is unsealed. Skipping..."
                      continue
                    fi

                    echo "vault is sealed. Unsealing..."

                    if [ ! -n "$unseal_key_0" ]; then echo "unseal_key_0 is not set"; exit 1; fi
                    vault operator unseal $unseal_key_0
                    if [ ! -n "$unseal_key_1" ]; then echo "unseal_key_1 is not set"; exit 1; fi
                    vault operator unseal $unseal_key_1
                    if [ ! -n "$unseal_key_2" ]; then echo "unseal_key_2 is not set"; exit 1; fi
                    vault operator unseal $unseal_key_2
                  done
              env:
                - name: unseal_key_0
                  valueFrom:
                    secretKeyRef:
                      name: vault-unseal-keys
                      key: unseal-key-0
                - name: unseal_key_1
                  valueFrom:
                    secretKeyRef:
                      name: vault-unseal-keys
                      key: unseal-key-1
                - name: unseal_key_2
                  valueFrom:
                    secretKeyRef:
                      name: vault-unseal-keys
                      key: unseal-key-2
