---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dkhptd-mongo-v2-conf
  namespace: dkhptd
data:
  mongod.conf: |
    # configmap
    net:
      port: 27017
      bindIp: 0.0.0.0
    security:
      authorization: disabled
    storage:
      wiredTiger:
        engineConfig:
          cacheSizeGB: 2
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-v2
  namespace: dkhptd
spec:
  replicas: 0
  serviceName: mongo-v2
  selector:
    matchLabels:
      app: mongo-v2
  template:
    metadata:
      labels:
        app: mongo-v2
    spec:
      containers:
        - name: mongo
          image: mongo:7.0
          command:
            - mongod
            - "--config"
            - "/etc/mongod.conf"
          volumeMounts:
            - name: mongo-data
              mountPath: /data/db
            - name: mongo-config
              mountPath: /etc/mongod.conf
              subPath: mongod.conf
          envFrom:
            - configMapRef:
                name: dkhptd-mongo-v2-env
          ports:
            - containerPort: 27017
      volumes:
        - name: mongo-config
          configMap:
            name: dkhptd-mongo-v2-conf
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        storageClassName: longhorn
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-v2
  namespace: dkhptd
  labels:
    app: mongo-v2
spec:
  clusterIP: None
  ports:
    - port: 27017
      name: mongo
  selector:
    app: mongo-v2
