apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
  namespace: dkhptd
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: dump
              image: mongo:7.0
              command:
                - "sh"
                - "-c"
                - |
                  mongodump --uri=${MONGO_CONNECTION_STRING} --out=/data/dump
              volumeMounts:
                - name: workdir
                  mountPath: /data
              envFrom:
                - configMapRef:
                    name: dkhptd-mongo-backup

            - name: zip
              image: busybox:latest
              command:
                - "sh"
                - "-c"
                - |
                  cd /data
                  tar -czvf dump.tar.gz dump
              volumeMounts:
                - name: workdir
                  mountPath: /data

            - name: upload
              image: amazon/aws-cli:latest
              command:
                - "sh"
                - "-c"
                - |
                  OBJECT_KEY=dkhptd/mongo-dump-$(date +'%Y.%m.%d').tar.gz
                  aws s3api --endpoint-url ${S3_ENDPOINT} put-object --bucket ${BUCKET_NAME} --key $OBJECT_KEY --body /data/dump.tar.gz
              envFrom:
                - configMapRef:
                    name: dkhptd-mongo-backup
              volumeMounts:
                - name: workdir
                  mountPath: /data

            - name: notify
              image: curlimages/curl:latest
              command:
                - sh
                - -c
                - |
                  OBJECT_KEY=dkhptd/mongo-dump-$(date +'%Y.%m.%d').tar.gz
                  MSG="SUCCESS backup-mongo ns: \`dkhptd\`"
                  curl -X POST "${DISCORD_WEBHOOK}" -H "Content-Type: application/json" -d "{\"content\":\"${MSG}\"}"
              envFrom:
                - configMapRef:
                    name: dkhptd-mongo-backup
              volumeMounts:
                - name: workdir
                  mountPath: /data

          containers:
            - name: dummy
              image: busybox:latest
              command: ["sh", "-c", "echo done"]

          restartPolicy: Never
          volumes:
            - name: workdir
              emptyDir: {}
