apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dkhptd-api-gateway
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-tuana9a-com
    kind: SecretStore
  target:
    name: dkhptd-api-gateway
  dataFrom:
    - extract:
        key: dkhptd/api-gateway/env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dkhptd-api-gateway
  namespace: dkhptd
data:
  BIND: 0.0.0.0
  PORT: "8080"
