apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dkhptd-scheduler
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-tuana9a-com
    kind: ClusterSecretStore
  target:
    name: dkhptd-scheduler
  dataFrom:
    - extract:
        key: dkhptd/scheduler/env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dkhptd-scheduler
  namespace: dkhptd
data:
  HELLO: WORLD # dummy
