---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkhptd-worker
spec:
  # replicas: 1 # auto-scaling
  selector:
    matchLabels:
      app: dkhptd-worker
  template:
    metadata:
      labels:
        app: dkhptd-worker
    spec:
      containers:
        - name: dkhptd-worker
          image: tuana9a/dkhptd-worker:2024.05.11.053520
          envFrom:
            - configMapRef:
                name: dkhptd-worker
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "500Mi"
              cpu: "500m"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dkhptd-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dkhptd-worker
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
