apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dkhptd-worker
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-tuana9a-com
    kind: ClusterSecretStore
  target:
    name: dkhptd-worker
  dataFrom:
    - extract:
        key: dkhptd/worker/env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dkhptd-worker
data:
  PUPPETEER_LAUNCH_OPTIONS_TYPE: docker
