apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hcr-workdir
spec:
  storageClassName: proxmox-data-xfs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hcr-workdir-setup
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: hcr-workdir
          persistentVolumeClaim:
            claimName: hcr-workdir
      initContainers:
        - name: repo
          image: alpine/git
          volumeMounts:
            - name: hcr-workdir
              mountPath: /app
          command:
            - "/bin/sh"
            - "-c"
            - |
              mkdir -p /app/hust-captcha-resolver
              rm -r /tmp/dkhptd || echo "ok: /tmp/dkhptd not found"
              git clone https://github.com/tuana9a/dkhptd /tmp/dkhptd
              cp -r /tmp/dkhptd/hust-captcha-resolver/* /app/hust-captcha-resolver
              rm -r /tmp/dkhptd
              ls -lha /app/
              ls -lha /app/hust-captcha-resolver/
        - name: weights
          image: alpine/curl
          volumeMounts:
            - name: hcr-workdir
              mountPath: /app
          command:
            - "/bin/sh"
            - "-c"
            - |
              rm /app/hust-captcha-resolver/weights*.pth
              curl -sSo /app/hust-captcha-resolver/weights-2021.04.05.pth https://public.tuana9a.com/hust-captcha-resolver/weights-2021.04.05.pth
              ls -lha /app/hust-captcha-resolver/
        - name: venv
          image: python:3.8-slim-bullseye
          workingDir: /app/hust-captcha-resolver
          volumeMounts:
            - name: hcr-workdir
              mountPath: /app
          command:
            - "/bin/sh"
            - "-c"
            - |
              python3 -m venv .venv
              .venv/bin/pip install -r requirements.txt
      containers:
        - name: dummy
          image: alpine
          command: ["echo", "done"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hcr
  template:
    metadata:
      labels:
        app: hcr
    spec:
      volumes:
        - name: hcr-workdir
          persistentVolumeClaim:
            claimName: hcr-workdir
      containers:
        - image: python:3.8-slim-bullseye
          name: hcr
          workingDir: /app/hust-captcha-resolver
          volumeMounts:
            - name: hcr-workdir
              mountPath: /app
          command: [".venv/bin/python", "main.py"]
          env:
            - name: DEVICE
              value: "cpu"
            - name: BIND
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1000Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: "/"
          livenessProbe:
            tcpSocket:
              port: 8080
---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: hcr
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: hcr
#   minReplicas: 1
#   maxReplicas: 5
#   metrics:
#     - type: Resource
#       resource:
#         name: cpu
#         target:
#           type: Utilization
#           averageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hcr
spec:
  selector:
    app: hcr
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hcr
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hcr.tuana9a.com
      secretName: hcr-tuana9a-com-tls
  rules:
    - host: hcr.tuana9a.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hcr
                port:
                  number: 8080
