apiVersion: v1
kind: Namespace
metadata:
  name: knative-eventing
---
apiVersion: operator.knative.dev/v1beta1
kind: KnativeEventing
metadata:
  name: knative-eventing
  namespace: knative-eventing # this namespace is hardcoded afaik
spec:
  version: "1.14.2"
  podDisruptionBudgets:
    - name: eventing-webhook
      minAvailable: 0
  workloads:
    - name: eventing-controller
      resources:
        - container: eventing-controller
          requests:
            cpu: 10m
            memory: 250M
          limits:
            cpu: 100m
            memory: 250M
    - name: eventing-webhook
      resources:
        - container: eventing-webhook
          requests:
            cpu: 10m
            memory: 250M
          limits:
            cpu: 100m
            memory: 250M
    - name: kafka-controller
      resources:
        - container: controller
          requests:
            cpu: 10m
            memory: 150M
          limits:
            cpu: 100m
            memory: 150M
    - name: mt-broker-controller
      resources:
        - container: mt-broker-controller
          requests:
            cpu: 10m
            memory: 100M
          limits:
            cpu: 100m
            memory: 100M
    - name: mt-broker-filter
      resources:
        - container: filter
          requests:
            cpu: 10m
            memory: 100M
          limits:
            cpu: 100m
            memory: 100M
    - name: mt-broker-ingress
      resources:
        - container: ingress
          requests:
            cpu: 10m
            memory: 100M
          limits:
            cpu: 100m
            memory: 100M
    - name: imc-controller
      resources:
        - container: controller
          requests:
            cpu: 10m
            memory: 100M
          limits:
            cpu: 100m
            memory: 100M
    - name: imc-dispatcher
      resources:
        - container: dispatcher
          requests:
            cpu: 10m
            memory: 100M
          limits:
            cpu: 100m
            memory: 100M
