apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-jcasc
  namespace: jenkins
  labels:
    jenkins-jenkins-config: "true"
data:
  oidc.yaml: |
    credentials:
      system:
        domainCredentials:
          - credentials:
              - idTokenFile:
                  id: gcp-oidc-id-token
                  scope: GLOBAL
                  audience: "https://iam.googleapis.com/projects/474326114337/locations/global/workloadIdentityPools/jenkins/providers/jenkins-tuana9a-com"
              - idTokenFile:
                  id: aws-oidc-id-token
                  scope: GLOBAL
                  audience: "sts.amazonaws.com"
    jobs:
      - script: |
          pipelineJob('test-gcp-oidc') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('cicd-ansible')
                  }
                }
                scriptPath(".jenkins/test-gcp-oidc.Jenkinsfile")
              }
            }
          }
      - script: |
          pipelineJob('test-aws-oidc') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('cicd-ansible')
                  }
                }
                scriptPath(".jenkins/test-aws-oidc.Jenkinsfile")
              }
            }
          }
