apiVersion: v1
kind: ConfigMap
metadata:
  name: test-oidc-jcasc
  namespace: jenkins
  labels:
    jenkins-jenkins-config: "true"
data:
  test-oidc.yaml: |
    jobs:
      - script: |
          pipelineJob('test-gcp-oidc') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('main')
                  }
                }
                scriptPath(".jenkins/test-gcp-oidc.Jenkinsfile")
              }
            }
          }
      - script: |
          pipelineJob('test-aws-oidc') {
            properties {
              pipelineTriggers {
                triggers {
                  cron {
                    spec('0 0 * * *')
                  }
                }
              }
            }
            definition {
              cpsScm {
                scm {
                  git {
                    remote {
                      url('https://github.com/tuana9a/platform.git')
                    }
                    branch('main')
                  }
                }
                scriptPath(".jenkins/test-aws-oidc.Jenkinsfile")
              }
            }
          }
