apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-vdc
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner-vdc
parameters:
  archiveOnDelete: "false"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner-vdc
  labels:
    app: nfs-client-provisioner-vdc
  # replace with namespace where provisioner is deployed
  namespace: nfs-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner-vdc
  template:
    metadata:
      labels:
        app: nfs-client-provisioner-vdc
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: registry.k8s.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: k8s-sigs.io/nfs-subdir-external-provisioner-vdc
            - name: NFS_SERVER
              value: 192.168.56.7
            - name: NFS_PATH
              value: /exports/vdc/
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.56.7
            path: /exports/vdc/
