# ----------------------
# | install kubernetes |
# ----------------------
- hosts: k8s_cluster
  tasks:
    - name: Check for kubesetup completion flag
      ansible.builtin.stat:
        path: /opt/kubesetup_completed
      register: kubesetup_flag

    - name: Set completion variable based on file existence
      ansible.builtin.set_fact:
        kubesetup_completed: "{{ kubesetup_flag.stat.exists }}"

    # when we upgrade the k8s, updating runc, cni, containerd could be included
    # in the upgrade, so adding a condition to skip these installations for old
    # worker is necessary
    - import_tasks: ./tasks/install_runc.yml
      when: not kubesetup_completed
    - import_tasks: ./tasks/install_cni.yml
      when: not kubesetup_completed
    - import_tasks: ./tasks/install_containerd.yml
      when: not kubesetup_completed
    - import_tasks: ./tasks/kubesetup.yml
      when: not kubesetup_completed
    - name: Mark kubesetup as completed
      become: true
      ansible.builtin.copy:
        dest: /opt/kubesetup_completed
        content: "yes"

    - import_tasks: ./tasks/authorized_keys.yml

# ----------------
# | join cluster |
# ----------------
- hosts: k8s_cluster
  tasks:
    - import_tasks: ./tasks/kube_read_pki.yml
      when: "('control-plane' in roles) and ('cluster-operations' in roles)"
    - import_tasks: ./tasks/kubeadm_create_join_command.yml
      when: "('control-plane' in roles) and ('cluster-operations' in roles)"
    - name: copy facts
      set_fact:
        join_command: "{{ hostvars[cluster_operations_host].join_command }}"
        slurp_kube_pki_results: "{{ hostvars[cluster_operations_host].slurp_kube_pki_results }}"

    - name: Check for kube joined completion flag
      ansible.builtin.stat:
        path: /opt/kubejoined_completed
      register: kubejoined_flag

    - name: Set completion variable based on file existence
      ansible.builtin.set_fact:
        kube_joined: "{{ kubejoined_flag.stat.exists }}"

    - import_tasks: ./tasks/kube_write_pki.yml
      when: not kube_joined and ('control-plane' in roles)
    - import_tasks: ./tasks/kubeadm_join.yml
      when: not kube_joined

    - name: kubevip
      become: true
      when: "'control-plane' in roles"
      ansible.builtin.template:
        src: kubevip.yaml
        dest: /etc/kubernetes/manifests/kubevip.yaml
        owner: root
        group: root
        mode: "0644"

    - name: Mark kube joined as completed
      become: true
      ansible.builtin.copy:
        dest: /opt/kubejoined_completed
        content: "yes"

# ----------------
# | other stuffs |
# ----------------
- hosts: k8s_cluster
  tasks:
    - import_tasks: ./tasks/install_etcdcli.yml
      when: "'control-plane' in roles"
    - import_tasks: ./tasks/install_wireguard.yml
      when: wireguard_clients is defined
    - import_tasks: ./tasks/wireguard_client.yml
      when: wireguard_clients is defined

    # NOTE: kubectl label node (required for csi-proxmox plugin working correctly)
    # https://github.com/sergelogvinov/proxmox-csi-plugin/blob/main/docs/install.md#prepare-kubernetes-cluster
    # Proxmox CSI Plugin relies on the well-known Kubernetes topology node labels to define the disk location.
    #   topology.kubernetes.io/region - Cluster name, the name must be the same as in cloud config region name
    #   topology.kubernetes.io/zone - Proxmox node name
    - set_fact:
        kube_node_labels_str: |
          {% for host in groups['k8s_cluster'] %}
          {{ hostvars[host].nodename }}:
            - "topology.kubernetes.io/region={{ hostvars[host].pve_cluster }}"
            - "topology.kubernetes.io/zone={{ hostvars[host].pve_node }}"
          {% endfor %}
      when: "('control-plane' in roles) and ('cluster-operations' in roles)"
    - include_tasks: ./tasks/kubectl_label_node.yml
      vars:
        kube_node_labels: "{{ kube_node_labels_str | from_yaml }}"
      when: "('control-plane' in roles) and ('cluster-operations' in roles)"
