- hosts: k8s_cluster_operations
  tasks:
    - name: Prepare list of nodes where goodbye is true
      set_fact:
        goodbye_nodes_str: >-
          {% set nodes = [] %}
          {% for host in hostvars %}
            {% if hostvars[host].goodbye | default(false) == true %}
              {% set _ = nodes.append({
                'nodename': hostvars[host].nodename,
                'is_control_plane': hostvars[host].is_control_plane
              }) %}
            {% endif %}
          {% endfor %}
          {{ nodes }}

    - name: (STUPID) Convert string to object
      set_fact:
        goodbye_nodes: "{{ goodbye_nodes_str | trim }}"

    - include_tasks: ./tasks/kubectl_drain.yml
      loop: "{{ goodbye_nodes }}"
      vars:
        k8s_node_name: "{{ item.nodename }}"

    - include_tasks: ./tasks/etcd_member_remove.yml
      loop: "{{ goodbye_nodes }}"
      vars:
        k8s_node_name: "{{ item.nodename }}"
      when: "{{ item.is_control_plane | default(false) }}"

    - include_tasks: ./tasks/kubectl_delete_node.yml
      loop: "{{ goodbye_nodes }}"
      vars:
        k8s_node_name: "{{ item.nodename }}"

- hosts: k8s_cluster
  tasks:
    - import_tasks: ./tasks/kubeadm_reset.yml
      when: goodbye | default(false)
