- hosts: k8s_cluster
  tasks:
    - name: Set goodbye_hosts
      set_fact:
        goodbye_hosts: "{{ lookup('file', 'files/goodbye_hosts.yml') | from_yaml }}"

    - name: Set goodbye_nodes_str
      set_fact:
        goodbye_nodes_str: |
          {% for host in goodbye_hosts %}
          - nodename: "{{ hostvars[host].nodename }}"
            is_control_plane: "{{ 'control-plane' in hostvars[host].roles }}"
          {% endfor %}

    - name: Set goodbye_nodes
      set_fact:
        goodbye_nodes: "{{ goodbye_nodes_str | from_yaml }}"

    - include_tasks: ./tasks/kubectl_drain.yml
      when: "('control-plane' in roles) and ('cluster-operations' in roles)"
      loop: "{{ goodbye_nodes }}"
      vars:
        k8s_node_name: "{{ item.nodename }}"

    - include_tasks: ./tasks/etcd_member_remove.yml
      when: "{{ ('control-plane' in roles) and ('cluster-operations' in roles) and (item.is_control_plane) }}"
      loop: "{{ goodbye_nodes }}"
      vars:
        k8s_node_name: "{{ item.nodename }}"

    - include_tasks: ./tasks/kubectl_delete_node.yml
      when: "('control-plane' in roles) and ('cluster-operations' in roles)"
      loop: "{{ goodbye_nodes }}"
      vars:
        k8s_node_name: "{{ item.nodename }}"

    - import_tasks: ./tasks/kubeadm_reset.yml
      when: "inventory_hostname in goodbye_hosts"

    - name: Mark as kube orphaned
      become: true
      ansible.builtin.copy:
        dest: /opt/kube_orphaned
        content: "yes"