- hosts: first_control_plane
  vars:
    kubernetes_version_major: "1.31"
  tasks:
    - name: change package repository
      shell: |
        echo -n "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version_major }}/deb/ /" | sudo tee /etc/apt/sources.list.d/kubernetes.list
      register: change_package_repository_out
    - debug:
        msg: "{{ change_package_repository_out.stdout | split('\n') }}"
    - ansible.builtin.slurp:
        src: /etc/apt/sources.list.d/kubernetes.list
      register: apt_source_kubernetes
    - debug:
        msg: "{{ apt_source_kubernetes.content | b64decode }}"
    - name: Update package cache
      become: true
      ansible.builtin.apt:
        update_cache: yes
    - shell: |
        sudo apt-cache madison kubeadm
      register: available_versions
    - debug:
        msg: "{{ available_versions.stdout | split('\n') }}"
