- hosts: first_control_plane
  vars:
    kubernetes_version_major: "1.31"
    kubernetes_version_minor: "1.31.12"
  tasks:
    - name: upgrade kubeadm
      shell: |
        set -xeu
        sudo apt-mark unhold kubeadm
        sudo apt-get update && sudo apt-get install -y kubeadm='{{ kubernetes_version_minor }}-*'
        sudo apt-mark hold kubeadm
        kubeadm version
      register: upgrade_kubeadm
    - debug:
        msg: "{{ upgrade_kubeadm.stdout | split('\n') }}"
    - shell: |
        set -xeu
        sudo kubeadm upgrade plan
      register: kubeadm_upgrade_plan
    - debug:
        msg: "{{ kubeadm_upgrade_plan.stdout | split('\n') }}"
