- hosts: data_nodes
  vars:
    kubernetes_version_major: "1.31"
    kubernetes_version_minor: "1.31.12"
  tasks:
    - name: upgrade kubelet kubectl
      when: "nodename == nodename_target"
      shell: |
        set -xeu
        sudo apt-mark unhold kubelet kubectl
        sudo apt-get update && sudo apt-get install -y kubelet='{{ kubernetes_version_minor }}-*' kubectl='{{ kubernetes_version_minor }}-*'
        sudo apt-mark hold kubelet kubectl
      register: kubelet_kubectl_upgrade
    - debug:
        msg: "{{ kubelet_kubectl_upgrade.stdout | split('\n') }}"
      when: "nodename == nodename_target"
    - name: restart kubelet
      when: "nodename == nodename_target"
      shell: |
        set -xeu
        sudo systemctl daemon-reload
        sudo systemctl restart kubelet
