apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: zeus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zeus
subjects:
  - kind: ServiceAccount
    name: zeus
    namespace: default
roleRef:
  kind: ClusterRole
  name: god-hand
  apiGroup: rbac.authorization.k8s.io
