apiVersion: v1
kind: Namespace
metadata:
  name: metrics-server
---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana
---
apiVersion: v1
kind: Namespace
metadata:
  name: loki-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: prometheus
---
apiVersion: v1
kind: Namespace
metadata:
  name: promtail
---
apiVersion: v1
kind: Namespace
metadata:
  name: coder
---
apiVersion: v1
kind: Namespace
metadata:
  name: t9stbot
---
apiVersion: v1
kind: Namespace
metadata:
  name: dkhptd
---
apiVersion: v1
kind: Namespace
metadata:
  name: hcr
---
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-forwarder
