apiVersion: apps/v1
kind: Deployment
metadata:
  name: paste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paste
  template:
    metadata:
      labels:
        app: paste
    spec:
      containers:
        - image: tuana9a/paste-go:git-9021772f
          name: paste
          env:
            - name: BIND
              value: "0.0.0.0"
            - name: PORT
              value: "8080"
          resources:
            requests:
              memory: "250Mi"
              cpu: "50m"
            limits:
              memory: "300Mi"
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: "/"
          livenessProbe:
            tcpSocket:
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: paste
spec:
  selector:
    app: paste
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: paste
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - paste.tuana9a.com
      secretName: paste-tuana9a-com-tls
  rules:
    - host: paste.tuana9a.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: paste
                port:
                  number: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: paste-next
spec:
  parentRefs:
    - kind: ListenerSet
      name: paste-next
  hostnames:
    - paste-next.tuana9a.com
  rules:
    - backendRefs:
        - kind: Service
          name: paste
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
---
kind: ListenerSet
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: paste-next
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  parentRef:
    name: starscream
    namespace: envoy-gateway-system
  listeners:
    - name: https
      hostname: paste-next.tuana9a.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: paste-next-tuana9a-com-tls
    - name: http
      hostname: paste-next.tuana9a.com
      port: 80
      protocol: HTTP
