apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: uuid
  namespace: stuffs
spec:
  template:
    spec:
      containers:
        - image: tuana9a/uuid:git-af287c15e3b164a81fcf36e6a679c12d190d4cbe # break: migrate to golang
          env:
            - name: BIND
              value: "0.0.0.0"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uuid
  namespace: stuffs
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - uuid.stuffs.kn.tuana9a.com
      secretName: uuid-stuffs-kn-tuana9a-com-tls
  rules:
    - host: uuid.stuffs.kn.tuana9a.com
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: forward-kourier
                port:
                  number: 80
