apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    email: tuana9a@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            email: tuana9a@gmail.com
            apiTokenSecretRef:
              name: cloudflare-api-token
              # NOTE: secret is required to be in the same namespace as cert-manager deployment
              # otherwise it's will throw error secret not found when dns challenging
              key: api-token
