apiVersion: v1
kind: Pod
spec:
  containers:
    - name: shell
      image: ubuntu
      command:
        - sleep
      args:
        - infinity
      securityContext:
        # ubuntu runs as root by default, it is recommended or even mandatory in some environments (such as pod security admission "restricted") to run as a non-root user.
        runAsUser: 1000
    - name: ansible
      image: alpine/ansible:2.17.0
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: ansible
          mountPath: "/var/secrets"
          readOnly: true
  volumes:
    - name: ansible
      secret:
        secretName: ansible
        # https://stackoverflow.com/questions/61728030/kubernetes-volume-mount-permissions-incorrect-for-secret
        defaultMode: 384 # 600
