apiVersion: v1
kind: Pod
spec:
  containers:
    - name: ubuntu
      image: tuana9a/ubuntu:git-1d3169e
      command:
        - sleep
      args:
        - infinity
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      envFrom:
        - secretRef:
            name: backup-coder-postgres
      volumeMounts:
        - name: workdir
          mountPath: /workdir

    - name: postgres
      image: postgres:16
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: workdir
          mountPath: /workdir
      envFrom:
        - secretRef:
            name: backup-coder-postgres

    - name: awscli
      image: amazon/aws-cli:2.18.0
      command:
        - sleep
      args:
        - infinity
      envFrom:
        - secretRef:
            name: backup-coder-postgres
      volumeMounts:
        - name: workdir
          mountPath: /workdir

  restartPolicy: Never
  volumes:
    - name: workdir
      emptyDir: {}
