apiVersion: v1
kind: Pod
spec:
  containers:
    - name: etcd
      image: tuana9a/toolbox:etcd-3.5.15
      command:
        - sleep
      args:
        - infinity
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      volumeMounts:
        - name: secrets
          mountPath: "/var/secrets"
          readOnly: true
        - name: workdir
          mountPath: "/workdir"
    - name: awscli
      image: amazon/aws-cli:2.18.0
      command:
        - sleep
      args:
        - infinity
      volumeMounts:
        - name: secrets
          mountPath: "/var/secrets"
          readOnly: true
        - name: workdir
          mountPath: /workdir
  volumes:
    - name: secrets
      secret:
        secretName: backup-kubernetes
    - name: workdir
      emptyDir: {}
