apiVersion: v1
kind: Pod
spec:
  serviceAccountName: odin
  containers:
    - name: main
      image: tuana9a/terraform-plan-apply-notify:2026.01
      command:
        - sleep
      args:
        - infinity
      envFrom:
        - secretRef:
            name: terraform-plan-apply-notify
      volumeMounts:
        - name: workdir
          mountPath: /workdir
  restartPolicy: Never
  volumes:
    - name: workdir
      emptyDir: {}
