apiVersion: v1
kind: Pod
spec:
  serviceAccountName: odin
  containers:
    - name: terraform
      image: tuana9a/toolbox:terraform-1.7.1-and-all
      command:
        - sleep
      args:
        - infinity
      env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      envFrom:
        - secretRef:
            name: terraform-plan-apply-notify
      volumeMounts:
        - name: workdir
          mountPath: /workdir
  restartPolicy: Never
  volumes:
    - name: workdir
      emptyDir: {}
