apiVersion: v1
kind: Pod
spec:
  containers:
    - name: ubuntu
      image: tuana9a/ubuntu:git-1d3169e
      command: ["sleep", "infinity"]
      envFrom:
        - secretRef:
            name: vault-unseal-keys
      volumeMounts:
        - name: secrets
          mountPath: "/var/secrets"
          readOnly: true
        - name: workdir
          mountPath: "/workdir"
    - name: vault
      image: hashicorp/vault:1.17.2
      command: ["sleep", "infinity"]
      envFrom:
        - secretRef:
            name: vault-unseal-keys
      volumeMounts:
        - name: secrets
          mountPath: "/var/secrets"
          readOnly: true
        - name: workdir
          mountPath: "/workdir"
  volumes:
    - name: secrets
      secret:
        secretName: vault-unseal-keys
    - name: workdir
      emptyDir: {}
