apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-env
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-tuana9a-com
    kind: SecretStore
  target:
    name: coder-env
  dataFrom:
    - extract:
        key: coder/env
