apiVersion: v1
data:
  ClusterConfiguration: |
    apiVersion: kubeadm.k8s.io/v1beta4
    kind: ClusterConfiguration
    apiServer:
      extraArgs:
      - name: oidc-client-id
        value: 474326114337-h9kpe020anghtfn8450knt6ltnqnar3t.apps.googleusercontent.com
      - name: oidc-issuer-url
        value: https://accounts.google.com
      - name: feature-gates
        value: "ImageVolume=true"
    caCertificateValidityPeriod: 87600h0m0s
    certificateValidityPeriod: 8760h0m0s
    certificatesDir: /etc/kubernetes/pki
    clusterName: kubernetes
    controlPlaneEndpoint: 192.168.56.21:6443
    controllerManager: {}
    dns: {}
    encryptionAlgorithm: RSA-2048
    etcd:
      local:
        dataDir: /var/lib/etcd
    imageRepository: registry.k8s.io
    kubernetesVersion: v1.33.10
    networking:
      dnsDomain: cluster.local
      podSubnet: 10.244.0.0/16
      serviceSubnet: 10.233.0.0/16
    proxy:
      disabled: true
    scheduler: {}
kind: ConfigMap
metadata:
  creationTimestamp: "2024-04-17T08:13:32Z"
  name: kubeadm-config
  namespace: kube-system
  resourceVersion: "7847962739"
  uid: 2cdd0790-866e-4322-a0d7-ebc9f1720add
