apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: t9stbot
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-tuana9a-com
    kind: ClusterSecretStore
  target:
    name: t9stbot
  dataFrom:
    - extract:
        key: t9stbot/env
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: t9stbot
data:
  BIND_ADDRESS: 0.0.0.0
  PORT: "8080"
  TELEGRAM_AVAILABLE_COMMANDS: chatid,myid,help
  TELEGRAM_BOT_NAME: t9stbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: t9stbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: t9stbot
  template:
    metadata:
      labels:
        app: t9stbot
    spec:
      initContainers:
        - name: set-commands
          image: tuana9a/t9stbot:git-0def1da57f473450d4a1d103230d66a3b3ff47e1
          envFrom:
            - configMapRef:
                name: t9stbot
            - secretRef:
                name: t9stbot
          command: ["node", "set_my_commands.js"]
        - name: set-webhook
          image: tuana9a/t9stbot:git-0def1da57f473450d4a1d103230d66a3b3ff47e1
          envFrom:
            - configMapRef:
                name: t9stbot
            - secretRef:
                name: t9stbot
          command: ["node", "set_webhook.js"]
      containers:
        - name: t9stbot
          image: tuana9a/t9stbot:git-0def1da57f473450d4a1d103230d66a3b3ff47e1
          envFrom:
            - configMapRef:
                name: t9stbot
            - secretRef:
                name: t9stbot
          command: ["node", "main-webhook.js"]
---
apiVersion: v1
kind: Service
metadata:
  name: t9stbot
spec:
  selector:
    app: t9stbot
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
---
kind: ListenerSet
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: t9stbot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production-gatewayapi
spec:
  parentRef:
    name: starscream
    namespace: envoy-gateway-system
  listeners:
    - name: https
      hostname: t9stbot.tuana9a.com
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: t9stbot-tuana9a-com-tls
    - name: http
      hostname: t9stbot.tuana9a.com
      port: 80
      protocol: HTTP
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: t9stbot
spec:
  parentRefs:
    - kind: ListenerSet
      name: t9stbot
  hostnames:
    - t9stbot.tuana9a.com
  rules:
    - backendRefs:
        - kind: Service
          name: t9stbot
          port: 8080
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
