# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  instance_count = ENV["VG_COUNT"] || 4
  public_key_file = ENV["VG_PUBLIC_KEY_FILE"] || "#{Dir.home}/.ssh/id_rsa.pub"

  (1..instance_count).each do |instance_id|
    instance_name = "k8s-instance-#{instance_id}"
    
    # define a scope for each instance
    config.vm.define instance_name do |ins|
      ins.vm.box = "hashicorp/bionic64"
      ins.vm.hostname = instance_name
      ins.vm.network "private_network", ip: "192.168.56.#{20+instance_id}"

      ins.vm.provider "virtualbox" do |vb|
        vb.name = instance_name
        vb.memory = 4096
        vb.cpus = 2
      end

      ins.vm.provision "shell" do |s|
        public_key_content = File.readlines(public_key_file).first.strip
        s.inline = <<-SHELL
          echo #{public_key_content} >> /home/vagrant/.ssh/authorized_keys
        SHELL
      end

    end

  end

end