FROM codercom/enterprise-base:ubuntu

USER coder

RUN sudo apt update -y

# tmux
RUN sudo apt install -y tmux

# direnv
RUN sudo apt install -y direnv

# zoxide
RUN sudo wget -q https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh -O /opt/install-zoxide.sh \
    && sudo chmod +x /opt/install-zoxide.sh && sudo /opt/install-zoxide.sh --bin-dir /usr/local/bin/
