LANG=C.UTF-8

# prompt
export PS1='%(!.%B%F{red}.%B%F{green}%n@)%m %F{blue}%(!.%1~.%~) %(!.#.$)%k%b%f '

# history
HISTSIZE=9999

# direnv
eval "$(direnv hook zsh)"

# zoxide
eval "$(zoxide init zsh)"
alias cd=z
