coder:
  # You can specify any environment variables you'd like to pass to Coder
  # here. Coder consumes environment variables listed in
  # `coder server --help`, and these environment variables are also passed
  # to the workspace provisioner (so you can consume them in your Terraform
  # templates for auth keys etc.).
  #
  # Please keep in mind that you should not set `CODER_HTTP_ADDRESS`,
  # `CODER_TLS_ENABLE`, `CODER_TLS_CERT_FILE` or `CODER_TLS_KEY_FILE` as
  # they are already set by the Helm chart and will cause conflicts.
  serviceAccount:
    extraRules:
      - apiGroups: ["apps"]
        resources: ["statefulsets"]
        verbs:
          - create
          - delete
          - deletecollection
          - get
          - list
          - patch
          - update
          - watch
  # WARN: those two envs are hard coded, can not move it to configmap need to specify it right here
  env:
    - name: CODER_PG_CONNECTION_URL
      valueFrom:
        secretKeyRef:
          name: coder-env
          key: CODER_PG_CONNECTION_URL

    - name: CODER_OIDC_ALLOW_SIGNUPS
      value: "false"

    - name: CODER_OIDC_AUTH_URL_PARAMS
      value: '{"access_type": "offline", "prompt": "consent"}'

    - name: CODER_OIDC_CLIENT_ID
      valueFrom:
        secretKeyRef:
          name: coder-env
          key: CODER_OIDC_CLIENT_ID
    - name: CODER_OIDC_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: coder-env
          key: CODER_OIDC_CLIENT_SECRET

    - name: CODER_OIDC_EMAIL_DOMAIN
      value: "gmail.com"

    - name: CODER_OIDC_ICON_URL
      value: "/icon/google.svg"

    - name: CODER_OIDC_ISSUER_URL
      value: "https://accounts.google.com"

    - name: CODER_OIDC_SCOPES
      value: "openid,profile,email"

    - name: CODER_OIDC_SIGN_IN_TEXT
      value: "Sign in with Google"

    - name: CODER_PROMETHEUS_ADDRESS
      value: "0.0.0.0:2112"

    - name: CODER_ACCESS_URL
      value: "https://coder.tuana9a.com"

    - name: CODER_WILDCARD_ACCESS_URL
      value: "*.coder.tuana9a.com"

    - name: CODER_TELEMETRY_ENABLE
      value: "false"
  service:
    enable: true
    type: ClusterIP
  ingress:
    enable: true
    className: nginx
    host: coder.tuana9a.com
    wildcardHost: "*.coder.tuana9a.com"
    tls:
      enable: true
      secretName: coder-tuana9a-com-tls
      wildcardSecretName: wildcard-coder-tuana9a-com-tls
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production-cloudflare"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 100m
      memory: 2048Mi
  listenerset:
    enable: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-production-gatewayapi
    parentRef:
      name: starscream
      namespace: envoy-gateway-system
    listeners:
      - name: https
        hostname: coder.tuana9a.com
        port: 443
        protocol: HTTPS
        tls:
          mode: Terminate
          certificateRefs:
            - name: coder-tuana9a-com-tls
      - name: http # requires for cert http challenge
        hostname: coder.tuana9a.com
        port: 80
        protocol: HTTP
  httproute:
    # coder.httproute.enable -- Whether to create the HTTPRoute object. If using a
    # Gateway, we recommend not specifying coder.tls.secretNames as the Gateway
    # will handle TLS termination.
    enable: true
    # coder.httproute.parentRefs -- the parentRefs to bind the route to
    # - name: my-gw
    #   namespace: gateway-namespace
    #   # sectionName is optional to fix to a specific listener
    #   sectionName: listener-name
    # - kind: ListenerSet
    #   name: coder
    #   port: 80
    # - kind: ListenerSet
    #   name: coder
    #   port: 443
    parentRefs:
      - kind: ListenerSet
        name: coder # found via source code

    # coder.httproute.host -- The hostname to match on.
    # Be sure to also set CODER_ACCESS_URL within coder.env[]
    host: "coder.tuana9a.com"
    # coder.httproute.wildcardHost -- The wildcard hostname to match on. Should be
    # in the form "*.example.com" or "*-suffix.example.com". If you are using a
    # suffix after the wildcard, the suffix will be stripped from the created
    # ingress to ensure that it is a legal ingress host. Optional if not using
    # applications over subdomains.
    # Be sure to also set CODER_WILDCARD_ACCESS_URL within coder.env[]
    wildcardHost: "*.coder.tuana9a.com"
