USING_UFW=0
pivpnforceipv6route=0
IPv4dev=eth0
install_user=u
install_home=/home/u
VPN=wireguard
pivpnPORT=51820
pivpnDNS1=1.1.1.1
pivpnDNS2=1.0.0.1
pivpnHOST=megatron.tuana9a.com
INPUT_CHAIN_EDITED=0
FORWARD_CHAIN_EDITED=0
INPUT_CHAIN_EDITEDv6=
FORWARD_CHAIN_EDITEDv6=
pivpnPROTO=udp
pivpnMTU=1420
pivpnDEV=wg0
pivpnNET=10.20.26.0
subnetClass=24
pivpnenableipv6=0
ALLOWED_IPS="10.20.26.0/24"