#!/usr/bin/env python3

from string import Template

tmpl = """# generated by gen_node_pool_spot.py
resource "google_container_node_pool" "node_pool_spot_$instance_type_snake_case" {
  name     = "$${google_container_cluster.zero.name}-$instance_type_kebab_case"
  location = google_container_cluster.zero.location
  cluster  = google_container_cluster.zero.name

  autoscaling {
    total_min_node_count = $total_min_node_count
    total_max_node_count = $total_max_node_count
  }

  network_config {
    enable_private_nodes = true
  }

  node_config {
    spot         = $spot
    machine_type = "$instance_type"
    disk_size_gb = 20
  }
}
"""
tmpl = Template(tmpl)

node_pools = [
    {
        "instance_type": "e2-medium",
        "total_min_node_count": 0,
        "total_max_node_count": 2,
        "spot": "true",
    },
    {
        "instance_type": "e2-highcpu-2",
        "total_min_node_count": 0,
        "total_max_node_count": 2,
        "spot": "true",
    },
    {
        "instance_type": "e2-highcpu-4",
        "total_min_node_count": 0,
        "total_max_node_count": 2,
        "spot": "true",
    },
]

contents = []

for pool in node_pools:
    instance_type = pool["instance_type"]
    pool["instance_type_kebab_case"] = instance_type
    pool["instance_type_snake_case"] = instance_type.replace("-", "_")
    content = tmpl.substitute(pool)
    contents.append(content)

print("\n".join(contents))
