apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hcr-workdir
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: hcr-workdir-setup
spec:
  template:
    spec:
      restartPolicy: Never
      volumes:
        - name: hcr-workdir
          persistentVolumeClaim:
            claimName: hcr-workdir
      initContainers:
        - name: git-clone
          image: alpine/git
          volumeMounts:
            - name: hcr-workdir
              mountPath: /app
          command:
            - "/bin/sh"
            - "-c"
            - |
              if [ ! -d "/app/hust-captcha-resolver" ]; then
                mkdir -p /app/hust-captcha-resolver;
              fi;
              git clone https://github.com/tuana9a/hust-captcha-resolver /tmp/hust-captcha-resolver;
              cp -r /tmp/hust-captcha-resolver/* /app/hust-captcha-resolver;
              rm -r /tmp/hust-captcha-resolver
        - name: download-weights
          image: alpine/curl
          volumeMounts:
            - name: hcr-workdir
              mountPath: /app
          command:
            - "/bin/sh"
            - "-c"
            - |
              if [ ! -f "/app/hust-captcha-resolver/weights.pth" ]; then
                curl -o /app/hust-captcha-resolver/weights.pth https://public.tuana9a.com/hust-captcha-resolver/weights-2021.04.05.pth;
              fi;
        - name: setup-venv
          image: python:3.8-slim-bullseye
          workingDir: /app/hust-captcha-resolver
          volumeMounts:
            - name: hcr-workdir
              mountPath: /app
          command:
            - "/bin/sh"
            - "-c"
            - |
              if [ -d "/app/hust-captcha-resolver/.venv" ]; then
                rm -r /app/hust-captcha-resolver/.venv
              fi
              python3 -m venv .venv && .venv/bin/pip install -r requirements.txt;
      containers:
        - name: dummy
          image: hello-world
