apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hcr
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
    spec:
      containers:
        - image: tuana9a/hcr
          imagePullPolicy: Always
          env:
            - name: DEVICE
              value: "cpu"
          resources:
            requests:
              memory: "300Mi"
              cpu: "300m"
            limits:
              memory: "1500Mi"
              cpu: "1500m"
