apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hcr
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "0"
    spec:
      volumes:
        - name: hcr-workdir
          persistentVolumeClaim:
            claimName: hcr-workdir
      containers:
        - image: python:3.8-slim-bullseye
          imagePullPolicy: Always
          workingDir: /app/hust-captcha-resolver
          volumeMounts:
            - name: hcr-workdir
              mountPath: /app
          command: ["/bin/sh", "-c"]
          args: [".venv/bin/python main.py"]
          env:
            - name: DEVICE
              value: "cpu"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
