global:
  domain: argocd.tuana9a.com

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: false
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      external-dns.alpha.kubernetes.io/hostname: "argocd.tuana9a.com"
      external-dns.alpha.kubernetes.io/target: "zione.tuana9a.com"
    extraTls:
      - hosts:
          - argocd.tuana9a.com
        secretName: argocd-tuana9a-com-tls

  ingressGrpc:
    enabled: false
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-production"
      external-dns.alpha.kubernetes.io/hostname: "grpc.argocd.tuana9a.com"
      external-dns.alpha.kubernetes.io/target: "zione.tuana9a.com"
    extraTls:
      - hosts:
          - grpc.argocd.tuana9a.com
        secretName: grpc-argocd-tuana9a-com-tls
