HOST_NAME: nfs
parted:
  - dev_path: /dev/vdb
    mount_path: /exports/vdb/
  - dev_path: /dev/vdc
    mount_path: /exports/vdc/
nfs_server_exports:
  - path: /exports/vdb/
    config: /exports/vdb/ 192.168.56.0/24(rw,sync,no_root_squash,no_subtree_check)
  - path: /exports/vdc/
    config: /exports/vdc/ 192.168.56.0/24(rw,sync,no_root_squash,no_subtree_check)
backup_nfs_items:
  - name: coder
    path: "/exports/nfs-client/coder-home-*"
    excludes:
      - .git
      - .venv
      - .m2
      - .vscode-server
      - node_modules
      - .cache
      - .terraform
      - .tfenv
      - .angular
      - .nvm
      - .npm
      - .local
      - .oh-my-zsh
      - go/pkg
      - "*.lock"
      - "*tmp*"
      - "Python-*"
      - "amazon-corretto-*"
