name: "030-bizflycloud-firewalls"

on:
  workflow_dispatch:
  push:
    paths:
      - "030-bizflycloud-firewalls/**"
      - ".github/workflows/030-bizflycloud-firewalls-terraform-plan-apply*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-plan-apply-notify.yml
    with:
      WORKING_DIR: ${{ github.workflow }}
      add-missing-files: true
    secrets:
      VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}