name: gcp network nat tuana9a terraform apply

on:
  workflow_dispatch:
  push:
    paths:
      - "031-gcp-network-nat-tuana9a/**"
      - ".github/workflows/031-gcp-network-nat-tuana9a*"
    branches:
      - main

env:
  GCP_PROJECT_ID: tuana9a
  GCP_PROJECT_ID_NUM: 474326114337
  GCP_SERVICE_ACCOUNT: terraform-network-admin@tuana9a.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_POOL: github
  GCP_WORKLOAD_IDENTITY_POOL_PROVIDER: github-tuana9a
  WORKING_DIR: 031-gcp-network-nat-tuana9a/

jobs:
  terraform-apply:
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v2
        with:
          project_id: "${{ env.GCP_PROJECT_ID }}"
          workload_identity_provider: "projects/${{ env.GCP_PROJECT_ID_NUM }}/locations/global/workloadIdentityPools/${{ env.GCP_WORKLOAD_IDENTITY_POOL }}/providers/${{ env.GCP_WORKLOAD_IDENTITY_POOL_PROVIDER }}"
          service_account: "${{ env.GCP_SERVICE_ACCOUNT }}"
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.1"
      - id: init
        working-directory: "${{ env.WORKING_DIR }}"
        run: terraform init
      - id: apply
        working-directory: "${{ env.WORKING_DIR }}"
        run: terraform apply -auto-approve
      - id: notify
        name: notify
        run: |
          MESSAGE=":white_check_mark: ${{ github.workflow }}\\n$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -d "{\"content\":\"${MESSAGE}\"}"
