name: "163-csi-driver-nfs-storage-classes"

on:
  workflow_dispatch:
  push:
    paths:
      - "163-csi-driver-nfs-storage-classes/**"
      - ".github/workflows/163-csi-driver-nfs-storage-classes-terraform-plan-apply*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-plan-apply-notify.yml
    with:
      runs-on: self-hosted-0
      WORKING_DIR: ${{ github.workflow }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}