name: tuana9a/vn/hanoi/121-anor-londo-cluster/19-vault
'on':
  workflow_dispatch: null
  push:
    paths:
    - tuana9a/vn/hanoi/121-anor-londo-cluster/19-vault/**
    - 1786269848-tfaa*
    - '!tuana9a/vn/hanoi/121-anor-londo-cluster/19-vault/196-vault-config'
    branches:
    - rock-n-roll
jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/tfaa.yml
    with:
      runs-on: self-hosted-0
      WORKING_DIR: tuana9a/vn/hanoi/121-anor-londo-cluster/19-vault
      login-vault: in-cluster-sa
    secrets: inherit
