name: "200-cert-manager"

on:
  workflow_dispatch:
  push:
    paths:
      - "200-cert-manager/**"
      - ".github/workflows/200-cert-manager-terraform-plan-apply*"
    branches:
      - rock-n-roll

env:
  GCP_PROJECT_ID: tuana9a
  GCP_PROJECT_ID_NUM: 474326114337
  GCP_SERVICE_ACCOUNT: terraform-state-editor@tuana9a.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_POOL: github
  GCP_WORKLOAD_IDENTITY_POOL_PROVIDER: github-tuana9a
  PLAN_ARTIFACT_NAME: ${{ github.run_id }}-${{ github.run_attempt }}-terraform-plan
  WORKING_DIR: 200-cert-manager/

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-plan-apply-notify.yml
    with:
      runs-on: self-hosted-0
      WORKING_DIR: ${{ github.workflow }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}