name: "210-knative-k8s-cobi-tuana9a"

on:
  workflow_dispatch:
  push:
    paths:
      - "210-knative-k8s-cobi-tuana9a/**"
      - ".github/workflows/210-knative-k8s-cobi-tuana9a-terraform-plan-apply*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/terraform-plan-apply-notify.yml
    with:
      runs-on: self-hosted-0
      WORKING_DIR: ${{ github.workflow }}
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}