name: "atlantis-tle-global-005-aws-iam"

on:
  workflow_dispatch:
  push:
    paths:
      - "atlantis-tle/global/005-aws-iam/**"
      - ".github/workflows/atlantis-tle-global-005-aws-iam*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/tfaa.yml
    with:
      WORKING_DIR: atlantis-tle/global/005-aws-iam
      AWS_ASSUME_ROLE: arn:aws:iam::541645813908:role/github-workflow
    secrets: inherit
