name: "checks"

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check_terraform_fmt:
    runs-on: ubuntu-slim
    steps:
      - name: Install terraform
        run: |
          curl -sSL -o terraform.zip https://releases.hashicorp.com/terraform/1.15.8/terraform_1.15.8_linux_amd64.zip
          unzip -o terraform.zip -d "$RUNNER_TEMP/bin"
          chmod +x "$RUNNER_TEMP/bin/terraform"
          echo "$RUNNER_TEMP/bin" >> "$GITHUB_PATH"
      - uses: actions/checkout@v4
      - id: check_terraform_fmt
        run: ./scripts/check_terraform_fmt.sh
