name: "docker build push jenkins"

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: tuana9a
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Set BUILD_TAG
        working-directory: "docker/jenkins"
        run: |
          FULL_COMMIT_HASH="${{ github.sha }}"
          COMMIT_HASH_SHORT="${FULL_COMMIT_HASH:0:7}"
          echo "FULL_COMMIT_HASH=${FULL_COMMIT_HASH}" >> "$GITHUB_ENV"
          echo "COMMIT_HASH_SHORT=${COMMIT_HASH_SHORT}" >> "$GITHUB_ENV"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: docker/jenkins
          file: docker/jenkins/Dockerfile
          push: true
          tags: tuana9a/jenkins:git-${{ env.COMMIT_HASH_SHORT }},tuana9a/jenkins:git-${{ env.FULL_COMMIT_HASH }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - id: set-status-ok
        run: echo 'status=ok' >> $GITHUB_ENV

      - name: Notify
        if: ${{ always() }}
        run: |
          github_workflow="${{ github.workflow }}"
          workflow_name=$github_workflow
          build_url="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          MESSAGE="${status:-bad} $workflow_name \`tuana9a/jenkins:git-${{ env.COMMIT_HASH_SHORT }}\`, \`tuana9a/jenkins:git-${{ env.FULL_COMMIT_HASH }}\` $build_url"
          curl -X POST ${{ secrets.DISCORD_WEBHOOK }} -H "Content-Type: application/json" -d "{\"content\":\"${MESSAGE}\"}"
