name: "docker-build-push-openssh"

on:
  workflow_dispatch:

jobs:
  main:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      WORKING_DIR: docker/openssh
      IMAGE_NAME: tuana9a/openssh
      tag-commithash: true
      tag-monthly: true
      tag-daily: true
      tag-secondly: true
      push: true
    secrets:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
