name: "tuana9a-global-009-kms"

on:
  workflow_dispatch:
  push:
    paths:
      - "tuana9a/global/009-kms/**"
      - ".github/workflows/tuana9a-global-009-kms*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/tfaa.yml
    with:
      WORKING_DIR: tuana9a/global/009-kms
      AWS_ASSUME_ROLE: arn:aws:iam::384588864907:role/github-workflow
    secrets: inherit
