name: "tuana9a/global/806-do-uptime"

on:
  workflow_dispatch:
  push:
    paths:
      - "tuana9a/global/806-do-uptime/**"
      - ".github/workflows/tuana9a-global-806-do-uptime-tfaa*"
    branches:
      - rock-n-roll

jobs:
  main:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/tfaa.yml
    with:
      runs-on: self-hosted-0
      WORKING_DIR: ${{ github.workflow }}
      login-vault: "in-cluster-sa"
    secrets: inherit
